DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS houses;

CREATE TABLE houses (
  name VARCHAR(255),
  url VARCHAR(255),
  id SERIAL2 PRIMARY KEY
);

CREATE TABLE students (
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  age INT2,
  house_id INT2 REFERENCES houses ON DELETE CASCADE,
  id SERIAL8 PRIMARY KEY
);
